version: 2.1
orbs:
    codecov: codecov/codecov@1.1.3
    gh: circleci/github-cli@1.0.3
    browser-tools: circleci/browser-tools@1.2.4
jobs:
    build_library:
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - browser-tools/install-browser-tools
            - restore_cache:
                  keys:
                      - v2-dependencies-angular-{{ checksum "lab/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd lab
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - lab/node_modules
                  key: v2-dependencies-angular-{{ checksum "lab/yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:click
            - run:
                  name: Lint
                  command: |
                      yarn lint
           # - run:
           #       name: Test
           #       command: |
           #           cd lab && test:ci
            - run:
                  name: Build Library
                  command: |
                      yarn build
            - run:
                  name: Test Artifacts
                  command: |
                      yarn test:artifacts
            - run:
                name: NPM Package
                command: |
                      cd lab/dist && npm pack
            # Save the dist folder for use in future jobs.
            - persist_to_workspace:
                  root: .
                  paths:
                      - lab/dist

    # Builds the Showcase app using @brightlayer-ui/angular-components persisted in /dist folder.
    build_demo:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - restore_cache:
                  keys:
                      - v2-dependencies-angular-{{ checksum "demo/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd demo
                      yarn install --frozen-lockfile

                      # Install the packed version of @brightlayer-ui/angular-components
                      PACKAGED_VERSION=`node -p "require('../lab/dist/package.json').version"`
                      yarn add ../lab/dist/angular-blui-lab-$PACKAGED_VERSION.tgz
            - save_cache:
                  name: Save Cache
                  paths:
                      - demo/node_modules
                  key: v2-dependencies-angular-{{ checksum "demo/yarn.lock" }}
            - attach_workspace:
                  at: .
            - run:
                  name: Build Showcase
                  command: |
                      cd demo && yarn buld


    publish:
      docker:
        - image: cimg/node:14.19.0-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command: |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @blui-lab/angular
            command:  |
              yarn publish:package -b $CIRCLE_BRANCH
    tag:
      docker:
        - image: cimg/node:14.19.0-browsers
      steps:
        - checkout
        - gh/setup
        - run:
            name: Tag @brightlayer-ui/angular-components
            command: |
              yarn tag:package -b $CIRCLE_BRANCH

workflows:
    version: 2
    angular_library:
        jobs:
            - build_library
            - build_demo:
                requires:
                    - build_library
            - publish:
                requires:
                    - build_demo
                filters:
                    branches:
                        only:
                            - master
                            - dev
            - tag:
                requires:
                    - publish
                filters:
                    branches:
                        only:
                            - master
