version: 2.1
orbs:
    codecov: codecov/codecov@1.1.3
    gh: circleci/github-cli@1.0.3
    browser-tools: circleci/browser-tools@1.2.4
jobs:
    build_library:
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - browser-tools/install-browser-tools
            - restore_cache:
                  keys:
                      - v2-dependencies-angular-{{ checksum "components/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd components
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - components/node_modules
                  key: v2-dependencies-angular-{{ checksum "components/yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      cd components
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      cd components && yarn lint
            - run:
                  name: Test
                  command: |
                      yarn test:ci
            - run:
                  name: Build Library
                  command: |
                      yarn build
            - run:
                  name: Test Artifacts
                  command: |
                      yarn test:artifacts
            - run:
                name: NPM Package
                command: |
                      cd dist && npm pack
            # Save the dist folder for use in future jobs.
            - persist_to_workspace:
                  root: .
                  paths:
                      - dist
                      - components/coverage
    coverage_report:
        working_directory: ~/angular-component-library
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './components/coverage/lcov.info'
                token: dc22e69d-e76e-4c9c-92a4-92432b1033d4

    # Builds the Storybook app using @brightlayer-ui/angular-components persisted in /dist folder.
    build_storybook:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
            - DEV_BRANCH: dev
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - restore_cache:
                  keys:
                      - v2-dependencies-angular-{{ checksum "demos/storybook/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd demos/storybook
                      yarn install --frozen-lockfile

                      # Install the packed version of @brightlayer-ui/angular-components
                      PACKAGED_VERSION=`node -p "require('../../dist/package.json').version"`
                      yarn add ../../dist/brightlayer-ui-angular-components-$PACKAGED_VERSION.tgz
            - save_cache:
                  name: Save Cache
                  paths:
                      - demos/storybook/node_modules
                  key: v2-dependencies-angular-{{ checksum "demos/storybook/yarn.lock" }}
            - attach_workspace:
                  at: .
            - run:
                  name: Prettier Check
                  command: |
                      cd demos/storybook
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      cd demos/storybook
                      yarn lint
            - run:
                  name: Build Storybook
                  command: |
                      cd demos/storybook

                      # master and dev branches should configure Google Analytics IDs before the build.
                      if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then
                        STORYBOOK_GA_ID=$MASTER_GA
                      fi
                      if [ $CIRCLE_BRANCH == $DEV_BRANCH ]; then
                        STORYBOOK_GA_ID=$DEV_GA
                      fi

                      yarn build-storybook
                      cd storybook-static
                      touch .nojekyll
            - persist_to_workspace:
                  root: .
                  paths:
                      - demos/storybook/storybook-static

    # Builds the Showcase app using @brightlayer-ui/angular-components persisted in /dist folder.
    build_showcase:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: Initialize Submodule
                  command: |
                      git submodule init && git submodule update
            - restore_cache:
                  keys:
                      - v2-dependencies-angular-{{ checksum "demos/showcase/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd demos/showcase
                      yarn install --frozen-lockfile

                      # Install the packed version of @brightlayer-ui/angular-components
                      PACKAGED_VERSION=`node -p "require('../../dist/package.json').version"`
                      yarn add ../../dist/brightlayer-ui-angular-components-$PACKAGED_VERSION.tgz
            - save_cache:
                  name: Save Cache
                  paths:
                      - demos/showcase/node_modules
                  key: v2-dependencies-angular-{{ checksum "demos/showcase/yarn.lock" }}
            - attach_workspace:
                  at: .
            - run:
                  name: Build Showcase
                  command: |
                      cd demos/showcase
                      yarn build

    deploy_storybook:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
            - DEV_BRANCH: dev
            - DEV_TARGET: https://github.com/brightlayer-ui-components/angular-dev
            - MASTER_TARGET: https://github.com/brightlayer-ui-components/angular
            - GH_EMAIL: brightlayer-ui@eaton.com
            - GH_NAME: Brightlayer UI Agent
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                  name: Deploy Storybook
                  command: |
                      git config --global user.email "$GH_EMAIL"
                      git config --global user.name "$GH_NAME"

                      cd demos/storybook

                      if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then
                        git clone $MASTER_TARGET out
                      elif [ $CIRCLE_BRANCH == $DEV_BRANCH ]; then
                        git clone $DEV_TARGET out
                      else
                        echo Deploying feature branch to firebase: https://blui-storybook-ng-feature.web.app/index.html
                        yarn run deploy:feature
                        exit 0
                      fi

                      cd out
                      git rm -rf .
                      cd ..

                      cp -a storybook-static/. out/.
                      cd out

                      git add -A
                      git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
                      git push

    publish:
      docker:
        - image: cimg/node:14.19.0-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command: |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @brightlayer-ui/angular-components
            command:  |
              yarn publish:package -b $CIRCLE_BRANCH
    tag:
      docker:
        - image: cimg/node:14.19.0-browsers
      steps:
        - checkout
        - gh/setup
        - run:
            name: Tag @brightlayer-ui/angular-components
            command: |
              yarn tag:package -b $CIRCLE_BRANCH

workflows:
    version: 2
    angular_library:
        jobs:
            - build_library
            - build_showcase:
                requires:
                    - build_library
          #  - build_storybook:
          #      requires:
          #          - build_library
          #  - deploy_storybook:
          #      requires:
          #          - build_storybook
            - publish:
                requires:
                   # - build_storybook
                    - build_showcase
                filters:
                    branches:
                        only:
                            - master
                            - dev
            - tag:
                requires:
                    - publish
                filters:
                    branches:
                        only:
                            - master
            - coverage_report:
                requires:
                    - build_library
                filters:
                    branches:
                        only:
                            - master
